In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
df = DataFrame(np.arange(4 * 4).reshape((4, 4)))

#随即生成一个排列方式
blender = np.random.permutation(4)
blender

array([3, 0, 2, 1])

In [4]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
# 基于生成的排列方式对矩阵进行重新排列
df.take(blender)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7

#### 如果我们要做有放回的抽样怎么办？

In [7]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])

# Now lets create a random permuation WITH replacement using randint
shaker = np.random.randint(0, len(box), size = 10)

In [8]:
shaker

array([0, 1, 2, 2, 0, 2, 2, 1, 2, 0])

In [9]:
#Now lets grab from the box
hand_grabs = box.take(shaker)

In [10]:
hand_grabs

array([1, 2, 3, 3, 1, 3, 3, 2, 3, 1])